ids =['kg:/m/01s56h',
'kg:/m/027k4k',
'kg:/m/027wrc',
'kg:/m/03c_kl',
'kg:/m/03hw3',
'kg:/m/03w1t0',
'kg:/m/04sf1h',
'kg:/m/059s10',
'kg:/m/06rrc',
'kg:/m/0h62vyn',
'kg:/m/0h8m1sw',
'kg:/m/0h8mfkx',
'kg:/m/0hgrj75',
'kg:/m/0hgs839',
'kg:/m/0hgs9bq',
'kg:/m/0hgsbhn',
'kg:/m/0hgsbw3',
'kg:/m/0hgsf5m',
'kg:/m/0l_yv',
'kg:/m/032ltr',
'kg:/m/03nn83',
'kg:/m/03qkxs7',
'kg:/m/048dyx',
'kg:/m/0gfgss9',
'kg:/m/09kjlm',
'kg:/m/03nfch',
'kg:/m/02sb4j',
'kg:/m/0h8k3ng',
'kg:/m/013s93',
'kg:/m/072jc1',
'kg:/m/025xryy',
'kg:/m/019b80',
'kg:/m/01cmb2',
'kg:/m/02wv6h6',
'kg:/m/0hgnvwy',
'kg:/m/01bfm9',
'kg:/m/0hgpbgq',
'kg:/m/08k64l',
'kg:/m/0cp1w6l',
'kg:/m/0hgn_pr',
'kg:/m/0hgr6',
'kg:/m/02rr7b7',
'kg:/m/0fly7',
'kg:/m/04nk84',
'kg:/m/01d40f',
'kg:/m/01xqvb',
'kg:/m/02c66t',
'kg:/m/02jt0t',
'kg:/m/05sfw_',
'kg:/m/06hwcd',
'kg:/m/0hgrh95',
'kg:/m/0hgsb5g',
'kg:/m/0hgsh7k',
'kg:/m/04jq15f',
'kg:/m/078bm7',
'kg:/m/080hkjn',
'kg:/m/08ry3v',
'kg:/m/0hf58v5',
'kg:/m/0hgryjx',
'kg:/m/0hgrzkp',
'kg:/m/0n5v01m',
'kg:/m/01xf5',
'kg:/m/01940j',
'kg:/m/01wyb3',
'kg:/m/01xygc',
'kg:/m/03tvvb',
'kg:/m/032b3c',
'kg:/m/0dly90',
'kg:/m/01sdv7',
'kg:/m/04xz_5',
'kg:/m/01xyhv',
'kg:/m/027q1m',
'kg:/m/05trrf',
'kg:/m/06hd76',
'kg:/m/047vlmn',
'kg:/m/0hgs8s2',
'kg:/m/0hgslft',
'kg:/m/017ftj',
'kg:/m/0404d',
'kg:/m/02h19r',
'kg:/m/02dl1y',
'kg:/m/02wbtzl',
'kg:/m/06t241',
'kg:/m/0hgs54_',
'kg:/m/01n5_8',
'kg:/m/0174n1 ',
'kg:/m/0h8m0th',
'kg:/m/0h8m5r9',
'kg:/m/0hgp5bc',
'kg:/m/0hgr9by',
'kg:/m/0176mf',
'kg:/m/02_vjy',
'kg:/m/01r546',
'kg:/m/01xdjk']

names =['slip-on shoe',
'athletic shoe',
'skate shoe',
'snowshoe',
'horseshoe',
'wrestling shoe',
'oxford shoe',
'horseshoes',
'shoe',
'shoe store',
'running shoe',
'bicycle shoe',
'outdoor shoe',
'tennis shoe',
'walking shoe',
'hiking shoe',
'cross training shoe',
'bridal shoe',
'snowshoe',
'riding boot',
'cowboy boot',
'work boots',
'motorcycle boot',
'snow boot',
'sneakers',
'sandal',
'blouse',
'sweatshirt',
't-shirt',
'long-sleeved t-shirt',
'sportswear',
'sweater',
'miniskirt',
'skirt',
'dance skirt',
'shorts',
'active shorts',
'cargo pants',
'underpants',
'active pants',
'denim',
'carpenter jeans',
'jeans',
'leggings',
'dress',
'academic dress',
'wedding dress',
'little black dress',
'cocktail dress',
'dress shirt',
'dance dress',
'day dress',
'bridal party dress',
'tote bag',
'messenger bag',
'handbag',
'hobo bag',
'luggage & bags',
'business bag',
'shoulder bag',
'bag',
'clutch',
'backpack',
'trench coat',
'coat',
'overcoat',
'jacket',
'leather jacket',
'vest',
'blazer',
'suit',
'ghillie suit',
'hazmat suit',
'infant bodysuit',
'outerwear',
'swimsuit bottom',
'swimsuit top',
'sunglasses',
'Jewellery',
'scarf',
'hat',
'sun hat',
'party hat',
'costume hat',
'hard hat',
'glove',
'soccer goalie glove',
'bicycle glove',
'formal gloves',
'safety glove',
'belt',
'wallet',
'earrings',
'brooch']

image_dict = {}
def create_dict():
    for i in range(len(names)):
        image_dict[ids[i]] = names[i]
    return(image_dict)
